In [107]:
import json
import pandas as pd
import numpy as np

In [108]:


MPs = {}
with open('ProgramStructure_2.json') as json_file:
    data = json.load(json_file)
    for p in data:
        MPs[(p['organisation'], p['title'])] = p['programStructure']

print(MPs)

{('Arden University, Study Center Berlin', 'Data Analytics and Information Systems Management'): ['Data Design', 'Data Handling and Decision Making', 'Data Visualisation and Interpretation', 'IS and Business Strategy Alignment', 'Technology and Trend Monitoring', 'Project and Portfolio Management', 'Research Project'], ('WU Executive Academy', 'Master of Business Administration - Digital Transformation and Data Science'): ['Digital Transformation', 'Data Science: Concepts & Application Domains', 'Data Science: from Data Science to Big Data', 'Data Science: Trends & Outlook', 'Strategy in the Age of Disruption', 'Strategic Foresight', 'Organisational Design', 'Blockchain'], ('Nottingham Trent University Online', 'Online Master of Business Administration - Data Analytics'): ['Responsible Leadership', 'The Values-Led Organisation', 'Global Marketing Management', 'Operations Management', 'Organisations and People Management', 'Financial Management', 'Business Information and Decision Makin

In [109]:
explore_skills_keys = {
    
    'Stats': ['exploratory','stats', 'statistics', 'statistical', 'inferencial', 'inference', \
              'descriptive statistics', 'sampling', 'hypothesis testing'],
    'StatsModels': ['regression', 'least squares','time series', 'time-series', 'prediction modelling', \
                    'forecast', 'linear models'],
    'Exploratory Tools': ['excel', 'sas', 'spss', ' r ', 'R,', ' R.' ],
    'Econometrics': ['econometrics','econometric '],
    'Analysis': ['business analysis', 'data analysis']
    
    
}

In [110]:
skills_list = []
for k,v in explore_skills_keys.items():
    skills_list.append(k)
    for s in v:
        skills_list.append(s)
    
print(skills_list)

['Stats', 'exploratory', 'stats', 'statistics', 'statistical', 'inferencial', 'inference', 'descriptive statistics', 'sampling', 'hypothesis testing', 'StatsModels', 'regression', 'least squares', 'time series', 'time-series', 'prediction modelling', 'forecast', 'linear models', 'Exploratory Tools', 'excel', 'sas', 'spss', ' r ', 'R,', ' R.', 'Econometrics', 'econometrics', 'econometric ', 'Analysis', 'business analysis', 'data analysis']


In [119]:
skills_edited = ['exploratory', 'statistics', 'statistical', 'inference', 'inferecial', 'descriptive statistics', \
                'hypothesis testing', 'regression', 'linear models', 'time series', 'time-series', 'prediction modeling', \
                'forecast', 'excel', 'spreadsheet', 'sas', 'spss', ' R ', 'econometrics', 'econometric', 'business analysis', \
                'data analysis']

In [123]:
def find_skills_inMPs(subject,search_words):       
    # loop search words
    result = []
    for search_word in search_words:
        #print(search_word)
        if search_word.lower() in subject.lower():
            result_tup = (search_word, subject)
            result.append(result_tup)
    if len(result) > 0:
        return result
    else:
        return 0




subjects_all = {}
subjects = []

for k,v in MPs.items():
    for s in v:
        a = find_skills_inMPs(s, skills_edited)
        #print(a)
        if a != 0:
            for r in a:
                if r[0] in subjects_all.keys():
                    subjects_all[r[0]].append(r[1])
                else:
                    subjects_all[r[0]] = [r[1]]
                
print(subjects_all)
                
        


{'statistical': ['Statistical Approaches to Data Analysis', 'Foundation of Data Analytics and Statistical Programming', 'Statistical Data Mining', 'Statistical Theory and Methods', 'Statistical Learning', 'Statistical Methods for Data Scientists', 'Statistical analysis and modelling', 'Statistical Learning Theory', 'Statistical Signal Processing I: Estimation Theory', 'Analyze big data and make data-driven predictions through probabilistic modeling and statistical inference; identify and deploy appropriate modeling and methodologies in order to extract meaningful information for decision making', 'Statistical Data Analysis', 'Statistical Analysis', 'Statistical Methods for Data Scientists', 'Statistical Concepts, Methods and Tools', 'Statistical Techniques for Computational Scientists', 'Scientific and Statistical Visualization', 'Statistical Modelling and Inference', 'Quantitative and Statistical Methods', 'Statistical Models for Dependent Data', 'Statistical Data Science (substitutes

The top courses with similarity above the 0.75
exploratory data analysis 7
exploratory data analysis and visualisation 6
exploratory data analysis and visualization 6
statistics and exploratory data analysis 6
exploratory data analysis in archaeology 3


In [122]:
all_subjects = []
for k,v in subjects_all.items():
    all_subjects.extend(v)
#all_subjects = np.unique(all_subjects)

all_sub = [x.lower() for x in all_subjects if len(x) < 58 ]
print(all_sub)

['statistical approaches to data analysis', 'applied statistics for data analysis', 'foundation of data analytics and statistical programming', 'statistical data mining', 'statistical theory and methods', 'statistical learning', 'data analysis', 'analysis of algorithms', 'business process analysis & data modeling', 'applied functional analysis', 'predictive analysis', 'python for data analysis and scientific computing', 'panel data analysis of microeconomic decisions', 'statistical methods for data scientists', 'scientific data analysis', 'forming and analysis of data in intellectual systems', 'exploratory data analysis and visualisation', 'statistical analysis and modelling', 'data mining and analysis', 'quantitative business analysis and forecasting', 'statistical learning theory', 'statistical signal processing i: estimation theory', 'dynamic and static program analysis for software security', 'statistical data analysis', 'big and distributed data analysis', 'statistical analysis', 

In [115]:
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def get_cosine_sim(*strs): 
    vectors = [t for t in get_vectors(*strs)]
    return cosine_similarity(vectors)
    
def get_vectors(*strs):
    text = [t for t in strs]
    vectorizer = CountVectorizer(text)
    vectorizer.fit(text)
    return vectorizer.transform(text).toarray()

In [116]:
text1 = all_sub[3]
text2 = all_sub[4]
text3 = all_sub[5]

In [162]:
def show_most_common(subject_list, thres, top=10):
    similarity = get_cosine_sim(*subject_list)
    ind = np.where(similarity >= thres)[0].tolist()
    ind_count = {subject_list[x]:ind.count(x) for x in ind}
    tuple_count = [(k, v) for k, v in ind_count.items()]
    tsorted = sorted(tuple_count, key=lambda x: x[1], reverse=True)
    print("The top courses with similarity above the " + str(thres))
    if top > len(tsorted):
        top_sub = tsorted
    else:
        top_sub = tsorted[:top]
    return top_sub
        

        


In [193]:
def clean_sim_result(result_tuple):
    sub_res = [x[0] for x in result_tuple]
    sim_matrix = get_cosine_sim(*sub_res)
    index = np.where((sim_matrix>0.7)& (sim_matrix<0.999))
    
    if len(index[0]) > 0:
        cor = list(zip(index[0], index[1]))
        cor_nd = []
        for c in cor:
            if ((c[1], c[0]) not in cor_nd) & (c[0] != c[1]) & (c[0] not in [x[1] for x in cor_nd]):
                cor_nd.append(c)
        cor_clean = []
        for e in cor_nd:
            if e[0] not in cor_clean:
                cor_clean.append(e[0])
            if e[1] not in cor_clean:
                cor_clean.append(e[1])
        new_result = []
        for c in cor_clean:
            new_result.append(result_tuple[c])
        new_result = sorted(new_result, key=lambda x: x[1], reverse=True)
    else:
        new_result = result_tuple
    return new_result


In [216]:
def clean_sim_result1(result_tuple):
    sub_res = [x[0] for x in result_tuple]
    sim_matrix = get_cosine_sim(*sub_res)
    index = np.where(sim_matrix>0.7)
    
    if len(index[0]) > 0:
        cor = list(zip(index[0], index[1]))
        exclude = []
        for c in cor:
            if (c[1] != c[0]) & (c[1] not in exclude) &(c[0] not in exclude):
                exclude.append(c[1])
    
        #print(exclude)
        new_result = [x for i,x in enumerate(result_tuple) if i not in exclude]
    else:
        new_result = result_tuple
    return new_result

In [221]:
def results_to_dict(all_dict):
    result_dict = {}
    top_sub_list = []
    for k,v in all_dict.items():
        sub_list = [x.lower() for x in all_dict[k]]
        tuple_top = show_most_common(sub_list, 0.75, 20)
        tuple_top_clean = clean_sim_result(tuple_top)
        print("----------------" + str(k) + "-------------------" )
        print("-------------------------------------------------")
        for t in tuple_top_clean:
            print(t)
        print("-------------------------------------------------")
    
    

In [222]:
results_to_dict(subjects_all)

The top courses with similarity above the 0.75
----------------statistical-------------------
-------------------------------------------------
('statistical data analysis', 16)
('statistical methods', 13)
('statistical learning', 9)
('statistical analysis and modelling', 9)
('statistical inference', 9)
('statistical programming', 9)
('statistical methods for data science', 9)
('statistical learning and data mining', 8)
-------------------------------------------------
The top courses with similarity above the 0.75
----------------data analysis-------------------
-------------------------------------------------
('data analysis', 53)
-------------------------------------------------
The top courses with similarity above the 0.75
----------------statistics-------------------
-------------------------------------------------
('applied managerial statistics', 25)
('modern applied statistics', 24)
('statistics for data analytics', 23)
('probability and statistics for data science', 22)
('s

----------------time-series-------------------
-------------------------------------------------
('analysis of time-series data', 1)
('time-series analysis using sas', 1)
('time-series forecasting', 1)
-------------------------------------------------
The top courses with similarity above the 0.75
----------------excel-------------------
-------------------------------------------------
('the real-world focus of this program provides an excellent networking environment that can lead to internship and industry-led project opportunities.', 1)
-------------------------------------------------
The top courses with similarity above the 0.75
----------------descriptive statistics-------------------
-------------------------------------------------
('descriptive statistics and probability for data science', 2)
-------------------------------------------------


In [163]:
alltop = show_most_common(all_sub, 0.75, 20)


The top courses with similarity above the 0.75


In [166]:
result = clean_sim_result(alltop)
for r in result:
    print(r)

('data analysis', 48)
('data analysis and statistics', 34)
('statistics and data analysis', 34)
('statistical data analysis', 20)
('applied statistics and data analysis', 16)
('statistics and exploratory data\xa0analysis', 16)
('applied data analysis', 14)


In [209]:
#Exploratory
exploratory = [x.lower() for x in subjects_all['statistical']]

q = show_most_common(exploratory, 0.75, 20)
print(q)
result_tuple = q
sub_res = [x[0] for x in result_tuple]
sim_matrix = get_cosine_sim(*sub_res)
print(sim_matrix)
index = np.where((sim_matrix>0.7)& (sim_matrix<1.0))
print(index)
#t = clean_sim_result(q)
cor = list(zip(index[0], index[1]))
print(cor)
exclude = []
for c in cor:
    if (c[1] != c[0]) & (c[1] not in exclude) &(c[0] not in exclude):
        exclude.append(c[1])
    
print(exclude)
for i in range(len(q)):
    if i not in exclude:
        print(q[i])
        
new_result = [x for i,x in enumerate(q) if i not in exclude]
print(new_result)

The top courses with similarity above the 0.75
[('statistical data analysis', 16), ('statistical methods', 13), ('statistical methods i.', 13), ('statistical analysis', 12), ('data analysis and statistical methods', 10), ('statistical learning', 9), ('statistical analysis and modelling', 9), ('statistical modelling and inference', 9), ('statistical inference', 9), ('statistical modelling and analysis', 9), ('statistical programming', 9), ('statistical methods for data science', 9), ('data analytic methods (statistical analysis)', 9), ('multivariate statistical methods', 9), ('statistical methods in r', 9), ('advanced statistical methods', 9), ('computational statistical methods', 9), ('data analysis: statistical methods', 9), ('statistical learning and data mining', 8), ('statistical analysis of data analytics', 8)]
[[1.         0.40824829 0.40824829 0.81649658 0.77459667 0.40824829
  0.57735027 0.28867513 0.40824829 0.57735027 0.40824829 0.51639778
  0.77459667 0.33333333 0.33333333 0

In [197]:
mx = get_cosine_sim('statistical methods', 'statistical methods i.')
print(mx)

[[1. 1.]
 [1. 1.]]


TypeError: 'int' object is not iterable

In [185]:
exp_res = show_most_common(exploratory, 0.75, 20)
exp_res_1 = [x[0] for x in exp_res]

sim_matrix = get_cosine_sim(*exp_res_1)
print(sim_matrix)
index = np.where((sim_matrix>0.79)& (sim_matrix<0.999))
print(len(index))
cor = list(zip(index[0], index[1]))
print(cor)

The top courses with similarity above the 0.75
[[1.         0.6        0.51639778]
 [0.6        1.         0.51639778]
 [0.51639778 0.51639778 1.        ]]
2
[]


In [149]:
cor_nd = []
for c in cor:
    if ((c[1], c[0]) not in cor_nd) & (c[0] != c[1]) & (c[0] not in [x[1] for x in cor_nd]):
        cor_nd.append(c)
print(cor_nd)

[(1, 2), (1, 3)]


In [153]:
cor_clean = []
for e in cor_nd:
    print(e[0])
    if e[0] not in cor_clean:
        cor_clean.append(e[0])
    if e[1] not in cor_clean:
        cor_clean.append(e[1])
print(cor_clean)
    



1
1
[1, 2, 3]


In [98]:
mx = get_cosine_sim('data analysis and statistics', 'statistics and data analysis')
print(mx)

[[1. 1.]
 [1. 1.]]


In [22]:
print(np.where(mx == 1.))

(array([0]), array([0]))


In [23]:
sim_matrix = get_cosine_sim(*all_sub)

In [24]:
print(sim_matrix.shape)

(293, 293)


In [90]:
index = np.where(sim_matrix>0.8)
d = index[0].tolist()

d1 = {x:d.count(x) for x in d}
t1 = [(k, v) for k, v in d1.items()] 
tsorted = sorted(t1, key=lambda x: x[1], reverse=True)

#print(tsorted)
for i in range(10):
    print(all_sub[tsorted[i][0]])

advanced statistics for physics analysis
spatial data analysis
qualitative data analysis
statistical methods
social media analysis
statistical processing of signals
statistical learning - classification
data models and structured analysis
scientific and statistical visualization
advanced models complex system analysis


In [26]:
cor = list(zip(index[0], index[1]))

In [127]:
cor_nd = []
for c in cor:
    if ((c[1], c[0]) not in cor_nd) & (c[0] != c[1]):
        cor_nd.append(c)
print(len(cor_nd))

122


In [28]:
for c in cor_nd:
    print(all_sub[c[0]], all_sub[c[1]])

Advanced Analysis of Linked Health Data Introductory Analysis of Linked Health Data
Advanced Data Analysis Advanced Data Analysis  OR
Advanced Data Analysis Data Analysis
Advanced Statistical Methods Statistical Methods
Advanced Statistical Methods Statistical Methods I.
Advanced Statistical Methods Statistical methods
Advanced Statistical Methods for Data Scientists Statistical Methods for Data Scientists
Algorithm Design and Analysis Algorithm Design, Analysis, and Implementation
Analysis and Design of Information Systems Information Systems Analysis, Modeling, and Design
Analysis and Design of Information Systems Systems Analysis and Design
Applied Data Analysis Applied Multivariate Data Analysis
Applied Data Analysis Applied Survival Data Analysis
Applied Data Analysis Applied data analysis
Applied Data Analysis Data Analysis
Applied Multivariate Data Analysis Applied data analysis
Applied Multivariate Data Analysis Multivariate Data Analysis
Applied Regression Analysis Regression 

In [29]:
no_dub_ind = np.unique([c[0] for c in cor_nd])

In [30]:
print(no_dub_ind)

[  1   2   9  10  13  16  28  30  31  33  34  35  36  37  38  40  42  46
  50  51  55  60  61  62  69  70  73  74  78  79  80  85  86  89 108 116
 124 127 139 146 154 156 159 160 195 201 209 212 214 216 219 223 224 227
 228 229 233 235 243 246 260 265 266 274 276 277 281]


In [31]:
bud_ind = np.unique([c[1] for c in cor_nd if c[1] not in no_dub_ind])

In [32]:
print(bud_ind)

[  3  14  47  48  63  75  87  90 103 104 105 109 117 122 123 135 136 137
 140 157 158 163 170 174 177 181 186 196 199 217 220 232 247 248 249 257
 258 259 261 262 263 264 268 269 275 278 280 283 289]


In [33]:
all_sub1 = []
for x in range(len(all_sub)):
    if x not in bud_ind:
        all_sub1.append(all_sub[x])

In [34]:
print(len(all_sub1))

244


In [35]:
sim_matrix1 = get_cosine_sim(*all_sub1)

In [36]:
index1 = np.where(sim_matrix1>0.75)

In [37]:
cor1 = list(zip(index1[0], index1[1]))

In [38]:
cor_nd1 = []
for c in cor1:
    if ((c[1], c[0]) not in cor_nd1) & (c[0] != c[1]):
        cor_nd1.append(c)
print(cor_nd1)

[(2, 4), (2, 57), (8, 196), (8, 197), (14, 112), (14, 232), (17, 83), (19, 234), (26, 28), (26, 31), (26, 32), (26, 33), (26, 34), (26, 57), (28, 34), (31, 32), (31, 34), (31, 80), (31, 223), (31, 224), (32, 34), (33, 34), (34, 57), (35, 36), (36, 37), (36, 57), (37, 126), (38, 39), (38, 57), (41, 42), (42, 43), (42, 60), (46, 57), (47, 57), (51, 113), (51, 196), (51, 197), (56, 57), (57, 58), (57, 180), (58, 79), (64, 69), (64, 180), (64, 217), (69, 180), (72, 73), (72, 74), (73, 74), (75, 76), (80, 127), (80, 223), (80, 224), (81, 181), (81, 204), (98, 240), (105, 173), (105, 184), (112, 232), (127, 223), (135, 138), (137, 138), (137, 203), (138, 172), (139, 196), (139, 197), (149, 150), (172, 180), (173, 180), (174, 180), (180, 217), (181, 191), (181, 204), (183, 222), (187, 189), (187, 192), (187, 193), (192, 193), (196, 197), (196, 198), (197, 198), (200, 214), (200, 219), (214, 219), (223, 224), (231, 232), (234, 235), (234, 236)]


In [39]:
for c in cor_nd1:
    print(all_sub1[c[0]],"            ", all_sub1[c[1]])

Advanced Data Analysis              Advanced Methods in Data Analysis
Advanced Data Analysis              Data Analysis
Advanced Statistical Methods              Statistical Methods
Advanced Statistical Methods              Statistical Methods I.
Analysis and Design of Information Systems              Information Systems Analysis, Modeling, and Design
Analysis and Design of Information Systems              Systems Analysis and Design
Analysis of Algorithms              Design and Analysis of Algorithms
Analysis of Time-Series Data              Time Series Analysis
Applied Data Analysis              Applied Multivariate Data Analysis
Applied Data Analysis              Applied Statistics and Data Analysis
Applied Data Analysis              Applied Statistics for Data Analysis
Applied Data Analysis              Applied Survival Data Analysis
Applied Data Analysis              Applied data analysis
Applied Data Analysis              Data Analysis
Applied Multivariate Data Analysis         

In [40]:
print(len(cor_nd1))

87


In [41]:
cor2 = list(zip(index2[0], index2[1]))

NameError: name 'index2' is not defined

In [ ]:
cor_nd2 = []
for c in cor2:
    if ((c[1], c[0]) not in cor_nd2) & (c[0] != c[1]):
        cor_nd2.append(c)
print(cor_nd2)

In [ ]:
I need:
1. Most common courses for each category (similarity over 0.75). 
Course, #number of total repetitions, #number of repetitions > 0.85, #number of repetitions > 1.